/*
*   QUESTIONS FOR ENEAGRAM TEST
*/

const questions = [
    { 'type':1 , 'question': '' , 0 },
    { 'type':2 , 'question': '' , 0 },
    { 'type':3 , 'question': '' , 0 },
    { 'type':4 , 'question': '' , 0 },
    { 'type':5 , 'question': '' , 0 },
    { 'type':6 , 'question': '' , 0 },
    { 'type':7 , 'question': '' , 0 },
    { 'type':8 , 'question': '' , 0 },
    { 'type':9 , 'question': '' , 0 },
    { 'type':1 , 'question': '' , 0 },
    { 'type':2 , 'question': '' , 0 },
    { 'type':3 , 'question': '' , 0 },
    { 'type':4 , 'question': '' , 0 },
    { 'type':5 , 'question': '' , 0 },
    { 'type':6 , 'question': '' , 0 },
    { 'type':7 , 'question': '' , 0 },
    { 'type':8 , 'question': '' , 0 },
    { 'type':9 , 'question': '' , 0 },
    { 'type':1 , 'question': '' , 0 },
    { 'type':2 , 'question': '' , 0 },
    { 'type':3 , 'question': '' , 0 },
    { 'type':4 , 'question': '' , 0 },
    { 'type':5 , 'question': '' , 0 },
    { 'type':6 , 'question': '' , 0 },
    { 'type':7 , 'question': '' , 0 },
    { 'type':8 , 'question': '' , 0 },
    { 'type':9 , 'question': '' , 0 },
    { 'type':1 , 'question': '' , 0 },
    { 'type':2 , 'question': '' , 0 },
    { 'type':3 , 'question': '' , 0 },
    { 'type':4 , 'question': '' , 0 },
    { 'type':5 , 'question': '' , 0 },
    { 'type':6 , 'question': '' , 0 },
    { 'type':7 , 'question': '' , 0 },
    { 'type':8 , 'question': '' , 0 },
    { 'type':9 , 'question': '' , 0 },
    { 'type':1 , 'question': '' , 0 },
    { 'type':2 , 'question': '' , 0 },
    { 'type':3 , 'question': '' , 0 },
    { 'type':4 , 'question': '' , 0 },
    { 'type':5 , 'question': '' , 0 },
    { 'type':6 , 'question': '' , 0 },
    { 'type':7 , 'question': '' , 0 },
    { 'type':8 , 'question': '' , 0 },
    { 'type':9 , 'question': '' , 0 },
];

module.export = questions;